# generated by Git for Windows
test -f ~/.profile && . ~/.profile

alias proy='cd /c/Users/Gabriel/Documents/Proyectos'
alias edit-notas='subl /c/Users/Gabriel/Documents/Proyectos/notas'
alias notas='cat /c/Users/Gabriel/Documents/Proyectos/notas'
alias add-alias='subl /c/Users/Gabriel/.bash_profile'
alias docker-ql='docker stop $(docker ps -a -q); docker rm $(docker ps -a -q); docker rmi $(docker images -a -q) -f; docker images'

#PROYECTOS
alias intranet-modular='cd /c/Users/Gabriel/Documents/Proyectos/cl_i1_intranet_modular'
alias semantio='cd /c/Users/Gabriel/Documents/Proyectos/cl_semantio_twitter'
alias proba='cd /c/Users/Gabriel/Documents/Proyectos/cl_proba_backend'
alias pizza-pizza='cd /c/Users/Gabriel/Documents/Proyectos/cl_pizzapizza_responsive'
alias ccu='cd /c/Users/Gabriel/Documents/Proyectos/cl_ccu_intranet'
alias lechero='cd /c/Users/Gabriel/Documents/Proyectos/cl_nestle_lecheros'
alias global='cd /c/Users/Gabriel/Documents/Proyectos/cl_global_intranet'
alias eva='cd /c/Users/Gabriel/Documents/Proyectos/cl_sm_eva'
alias cozumel='cd /c/Users/Gabriel/Documents/Proyectos/cl_cozumel_sgh'
